### ISSUE TITLE
Start using case classes

### ISSUE THREAD

**Issue by hugoferreira** [luismfonseca/aom-pattern#1]
Should't an Entity, EntityType, etc, be a case class? http://www.scala-lang.org/node/107

A more profound question: shouldn't an Entity, EntityType, etc. be considered an Algebraic Data Type? http://gleichmann.wordpress.com/2011/01/30/functional-scala-algebraic-datatypes-enumerated-types/

**Comment by luismfonseca** [comment]
Done in 45230271d540ab2602b250b809e44236169f1340.
