### ISSUE TITLE
Universes have a precedence

### ISSUE THREAD

**Issue by hugoferreira** [luismfonseca/aom-pattern#3]
From the big-bang on, all the universes were created based on a previous one. Keep a reference to it.

**Comment by luismfonseca** [comment]
But if merges are to be considered, there can be a universe with 2 previous universes.

**Comment by hugoferreira** [comment]
Yes!!

Hugo Sereno Ferreira, PhD

On 18/10/2012, at 12:57, luismfonseca notifications@github.com wrote:

But if merges are to be considered, there can be a universe with 2 previous
universes.

—
Reply to this email directly or view it on
GitHubhttps://github.com/luismfonseca/aom-pattern/issues/3#issuecomment-9561762.

**Comment by luismfonseca** [comment]
Fixed in commit 5df32f1619c04b8384b0dda761485a0d05a3535a.
